# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/CPU_design/lab/lab3/cache_cpu_test/cache_cpu_test.srcs/sources_1/ip/BRAM/BRAM.xci
# IP: The module: 'BRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CPU_design/lab/lab3/cache_cpu_test/cache_cpu_test.srcs/sources_1/ip/BRAM/BRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/CPU_design/lab/lab3/cache_cpu_test/cache_cpu_test.srcs/sources_1/ip/BRAM/BRAM.xci
# IP: The module: 'BRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/CPU_design/lab/lab3/cache_cpu_test/cache_cpu_test.srcs/sources_1/ip/BRAM/BRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'BRAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
